import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} bg-white text-black`}>
      <body>
        <header className="p-4 sticky top-0 bg-transparent">
          <a href="https://www.roblox.com/games/91945887967211/the-canvas" className="decoration-wavy">The Canvas</a> by <a href="https://altie122.xyz/" className="decoration-wavy">DragonForgeRGS</a>
        </header>
        {children}
      </body>
    </html>
  );
}
