name: Hourly Snapshot

on:
  schedule:
    - cron: "0 */1 * * *" # Run every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - run: node scripts/hourlyfetch.js
        env:
          CREATE_API_KEY: ${{ secrets.CREATE_API_KEY }}
